services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: >
        sh c "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1'"
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      - .:/app
    command: >
          sh -c "alembic upgrade head &&
          uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
